version: '3.3'

services:
  mongodb:
    image: mongo:3.6.3-jessie
    environment:
      - MONGODB_DATA_DIR=/data/db
      - MONGODB_LOG_DIR=/dev/null
      - MONGODB_USER="mouse"
      - MONGODB_PASS="123qwe"
    volumes:
      - ./data-mongo/db:/data/db
#    ports:
#      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
  app:
    image: node:8.9.4
    environment:
      - "TZ=Asia/Bangkok"
    volumes:
      - ./:/var/www/html/app
    links:
      - mongodb
    depends_on:
      - mongodb
    working_dir: /var/www/html/app
    command: >
       bash -c "npm install && npm start"
#    ports:
#      - 3000:4000
  nginx:
    image: nginx:1.13.3
    volumes:
      - ./server/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
volumes:
  typescript-mongoose-express:
